CREATE TABLE [Person] (
	ID INT IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Nickname VARCHAR(255) NOT NULL, 
	PRIMARY KEY (ID)
);

CREATE TABLE [Club] (
	ID INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	OwnerPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (OwnerPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [MemberOf] (
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	Admin BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY (PersonID, ClubID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID)
);

CREATE TABLE [GameType] (
	ID INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	ScoreMoniker VARCHAR(255) NOT NULL,
	IsZeroSum BIT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE [Game] (
	ID INT IDENTITY(1,1) NOT NULL,
	ClubID INT NOT NULL,
	GameTypeID INT NOT NULL,
	StartDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	EndDate DATETIME NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID),
	FOREIGN KEY (GameTypeID) REFERENCES [GameType](ID)
);

CREATE TABLE [GameRecord] (
	ID INT IDENTITY(1,1) NOT NULL,
	GameID INT NOT NULL,
	PersonID INT NOT NULL,
	ScoreChange INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (GameID) REFERENCES [Game](ID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID)
);
