USE [master];
CREATE DATABASE [stats];
GO

USE [stats];

CREATE TABLE [Person] (
	ID INT IDENTITY(1,1) NOT NULL,
	Username VARCHAR(255) NOT NULL,
	FirstName VARCHAR(255) NULL,
	LastName VARCHAR(255) NULL,
	Nickname VARCHAR(255) NULL, 
	PRIMARY KEY (ID)
);

CREATE TABLE [AuthLocal] {
	PersonID INT NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL
	PRIMARY KEY (PersonID)
	FOREIGN KEY (PersonID) REFERENCES [Person](ID)
	CONSTRAINT AK_Email UNIQUE(Email)
};

CREATE TABLE [AuthGoogle] (
	AuthID VARCHAR(255) NOT NULL, 
	PersonID INT NULL,
	PRIMARY KEY (AuthID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID)
);

CREATE TABLE [Friendship] (
	PersonID INT NOT NULL,
	TargetPersonID INT NOT NULL,
	IsFriend BIT NOT NULL,
	IsBlocking BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY (PersonID, TargetPersonID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (TargetPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [Club] (
	ID INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	OwnerPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (OwnerPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [Membership] (
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	IsCashAdmin BIT DEFAULT 0 NOT NULL,
	IsGameAdmin BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY (PersonID, ClubID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID)
);

CREATE TABLE [GameType] (
	ID INT IDENTITY(1,1) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	IsCash BIT NOT NULL,
	IsZeroSum BIT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE [Game] (
	ID INT IDENTITY(1,1) NOT NULL,
	ClubID INT NOT NULL,
	GameTypeID INT NOT NULL,
	StartDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	EndDate DATETIME NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID),
	FOREIGN KEY (GameTypeID) REFERENCES [GameType](ID)
);

CREATE TABLE [GameRecord] (
	ID INT IDENTITY(1,1) NOT NULL,
	GameID INT NOT NULL,
	PersonID INT NOT NULL,
	ScoreChange INT NOT NULL,
	CreatedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CreatedByPersonID INT NOT NULL,
	ModifiedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ModifiedByPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (GameID) REFERENCES [Game](ID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (CreatedByPersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ModifiedByPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [GameRecordAudit] (
	ID INT IDENTITY(1,1) NOT NULL,
	GameRecordID INT NOT NULL,
	GameID INT NOT NULL,
	PersonID INT NOT NULL,
	ScoreChange INT NOT NULL,
	ModifiedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ModifiedByPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (GameRecordID) REFERENCES [GameRecord](ID),
	FOREIGN KEY (GameID) REFERENCES [Game](ID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ModifiedByPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [Score] (
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	GameTypeID INT NOT NULL,
	Total INT NOT NULL,
	PRIMARY KEY (PersonID, ClubID, GameTypeID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID),
	FOREIGN KEY (GameTypeID) REFERENCES [GameType](ID)
);

CREATE TABLE [CashTransaction] (
	ID INT IDENTITY(1,1) NOT NULL,
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	CashChange INT NOT NULL,
	CreatedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CreatedByPersonID INT NOT NULL,
	ModifiedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ModifiedByPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID),
	FOREIGN KEY (CreatedByPersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ModifiedByPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [CashTransactionAudit] (
	ID INT IDENTITY(1,1) NOT NULL,
	CashTransactionID INT NOT NULL,
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	CashChange INT NOT NULL,
	ModifiedTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ModifiedByPersonID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CashTransactionID) REFERENCES [CashTransaction](ID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID),
	FOREIGN KEY (ModifiedByPersonID) REFERENCES [Person](ID)
);

CREATE TABLE [Cash] (
	PersonID INT NOT NULL,
	ClubID INT NOT NULL,
	Total INT NOT NULL,
	PRIMARY KEY (PersonID, ClubID),
	FOREIGN KEY (PersonID) REFERENCES [Person](ID),
	FOREIGN KEY (ClubID) REFERENCES [Club](ID)
);